platform :ios, '7.0' 
pod 'RestKit', '~> 0.20.0'
pod 'SVProgressHUD'
pod 'MCSwipeTableViewCell'
pod 'Canvas', '~> 0.1'
pod 'KNMultiItemSelector'
pod 'Reveal-iOS-SDK'
pod 'MagicalRecord'
pod 'CKCalendar'